/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Client = IDL.Principal;
export const Booking = IDL.Record({
  'service' : Service,
  'client' : Client,
  'isNight' : IDL.Bool,
  'date' : IDL.Text,
  'time' : IDL.Int,
  'price' : IDL.Int,
  'salonName' : IDL.Text,
  'isSunday' : IDL.Bool,
});
export const LoyaltyTier = IDL.Record({
  'tierName' : IDL.Text,
  'requiredXP' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'tier' : LoyaltyTier,
});
export const Availability = IDL.Record({
  'day' : IDL.Text,
  'isNight' : IDL.Bool,
  'date' : IDL.Text,
  'time' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'isSunday' : IDL.Bool,
});
export const Salon = IDL.Record({
  'photoUrls' : IDL.Vec(IDL.Text),
  'owner' : IDL.Principal,
  'isPremium' : IDL.Bool,
  'neighborhood' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'availabilities' : IDL.Vec(Availability),
  'services' : IDL.Vec(Service),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookSalon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'createSalon' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(Service),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'ensureSalonsSeeded' : IDL.Func([], [], []),
  'getBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoyaltyProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getSalon' : IDL.Func([IDL.Text], [Salon], ['query']),
  'getSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetLoyaltyProfiles' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Service = IDL.Record({
    'name' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Client = IDL.Principal;
  const Booking = IDL.Record({
    'service' : Service,
    'client' : Client,
    'isNight' : IDL.Bool,
    'date' : IDL.Text,
    'time' : IDL.Int,
    'price' : IDL.Int,
    'salonName' : IDL.Text,
    'isSunday' : IDL.Bool,
  });
  const LoyaltyTier = IDL.Record({
    'tierName' : IDL.Text,
    'requiredXP' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'tier' : LoyaltyTier,
  });
  const Availability = IDL.Record({
    'day' : IDL.Text,
    'isNight' : IDL.Bool,
    'date' : IDL.Text,
    'time' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'isSunday' : IDL.Bool,
  });
  const Salon = IDL.Record({
    'photoUrls' : IDL.Vec(IDL.Text),
    'owner' : IDL.Principal,
    'isPremium' : IDL.Bool,
    'neighborhood' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'availabilities' : IDL.Vec(Availability),
    'services' : IDL.Vec(Service),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookSalon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'createSalon' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(Service),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'ensureSalonsSeeded' : IDL.Func([], [], []),
    'getBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoyaltyProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getSalon' : IDL.Func([IDL.Text], [Salon], ['query']),
    'getSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetLoyaltyProfiles' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };