/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Availability {
  'day' : string,
  'isNight' : boolean,
  'date' : string,
  'time' : bigint,
  'isAvailable' : boolean,
  'isSunday' : boolean,
}
export interface Booking {
  'service' : Service,
  'client' : Client,
  'isNight' : boolean,
  'date' : string,
  'time' : bigint,
  'price' : bigint,
  'salonName' : string,
  'isSunday' : boolean,
}
export type Client = Principal;
export interface LoyaltyTier { 'tierName' : string, 'requiredXP' : bigint }
export interface Salon {
  'photoUrls' : Array<string>,
  'owner' : Principal,
  'isPremium' : boolean,
  'neighborhood' : string,
  'name' : string,
  'description' : string,
  'availabilities' : Array<Availability>,
  'services' : Array<Service>,
}
export interface Service {
  'name' : string,
  'durationMinutes' : bigint,
  'price' : bigint,
}
export interface UserProfile {
  'xp' : bigint,
  'name' : string,
  'role' : string,
  'tier' : LoyaltyTier,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookSalon' : ActorMethod<[string, bigint, string, string], undefined>,
  'createSalon' : ActorMethod<
    [string, string, string, Array<string>, Array<Service>, boolean],
    undefined
  >,
  'ensureSalonsSeeded' : ActorMethod<[], undefined>,
  'getBookings' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLoyaltyProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getSalon' : ActorMethod<[string], Salon>,
  'getSalons' : ActorMethod<[], Array<Salon>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetLoyaltyProfiles' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];